version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-dependencies:
        update-types:
          - "patch"

  - package-ecosystem: "npm"
    directory: "/bench"
    schedule:
      interval: "weekly"
    groups:
      patch-dependencies:
        update-types:
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
