name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  NODE_OPTIONS: --test-reporter=tap

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run ci
      - run: npm test --silent | tee results.tap
        shell: bash -euo pipefail {0}

      - uses: nikeee/tap-summary@dist
        continue-on-error: true
        if: always()

  test-integration:
    if: ${{ github.event_name != 'pull_request' }}
    name: Integration Tests
    runs-on: ubuntu-latest

    needs: test

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - run: npm ci
      - run: npm run test:integration --silent | tee results.tap
        shell: bash -euo pipefail {0}
        env:
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_S3_REGION: ${{ secrets.AWS_S3_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_S3_SECRET_KEY: ${{ secrets.AWS_S3_SECRET_KEY }}

          CLOUDFLARE_S3_ENDPOINT: ${{ secrets.CLOUDFLARE_S3_ENDPOINT }}
          CLOUDFLARE_S3_REGION: ${{ secrets.CLOUDFLARE_S3_REGION }}
          CLOUDFLARE_S3_BUCKET: ${{ secrets.CLOUDFLARE_S3_BUCKET }}
          CLOUDFLARE_S3_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_S3_ACCESS_KEY_ID }}
          CLOUDFLARE_S3_SECRET_KEY: ${{ secrets.CLOUDFLARE_S3_SECRET_KEY }}

          HETZNER_S3_ENDPOINT: ${{ secrets.HETZNER_S3_ENDPOINT }}
          HETZNER_S3_REGION: ${{ secrets.HETZNER_S3_REGION }}
          HETZNER_S3_BUCKET: ${{ secrets.HETZNER_S3_BUCKET }}
          HETZNER_S3_ACCESS_KEY_ID: ${{ secrets.HETZNER_S3_ACCESS_KEY_ID }}
          HETZNER_S3_SECRET_KEY: ${{ secrets.HETZNER_S3_SECRET_KEY }}

      - uses: nikeee/tap-summary@dist
        continue-on-error: true
        if: always()

  docs-build:
    if: ${{ github.event_name != 'pull_request' }}
    name: Build Docs
    runs-on: ubuntu-latest

    needs: test-integration

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - run: npm ci
      - run: npm run docs
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs
